# Generated by Django 4.1.1 on 2022-09-07 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("7152a81c-e49a-438e-bfd5-fc6181f4b872"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("city", models.CharField(max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("street", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("number", models.PositiveIntegerField()),
            ],
        ),
    ]
