# Generated by Django 4.1.1 on 2022-09-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
    ]
