# Generated by Django 4.1.1 on 2022-09-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_remove_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
